services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT "app:create_app('production')"
    disk:
      name: portfolio-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:////data/portfolio.db